# Generated by Django 4.2.6 on 2023-10-25 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=20, prefix='LOAN', unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_term', models.IntegerField()),
                ('repayment_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('penalty_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('loan_account_no', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=25, prefix='217', unique=True)),
                ('loan_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('In-active', 'In-active'), ('In-arrears', 'In-arrears'), ('Paid-off', 'Paid-off'), ('Written-off', 'Written-off')], default='In-active', max_length=100)),
                ('payslip', models.ImageField(blank=True, null=True, upload_to='payslip')),
                ('credit_report', models.ImageField(blank=True, null=True, upload_to='credit_report')),
                ('loan_start', models.DateTimeField(blank=True, null=True)),
                ('loan_type', models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], default='Personal', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
