# Generated by Django 4.2.6 on 2023-10-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='interest_rate',
            new_name='interest_rate_percent',
        ),
    ]
