# Generated by Django 4.2.6 on 2023-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_interest_rate_loan_interest_rate_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
