# Generated by Django 4.2.6 on 2023-10-24 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PersonaLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_term', models.DecimalField(decimal_places=0, default=0.0, max_digits=4)),
                ('repayment_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('penalty_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('loan_account_no', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=25, prefix='217', unique=True)),
                ('loan_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('in-active', 'In-active'), ('in-arrears', 'In-arrears'), ('paid-off', 'Paid-off'), ('written-off', 'Written-off')], default='in-active', max_length=100)),
                ('payslip', models.ImageField(blank=True, null=True, upload_to='payslip')),
                ('credit_report', models.ImageField(blank=True, null=True, upload_to='credit_report')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kyc_submitted', models.BooleanField(default=False)),
                ('kyc_confirmed', models.BooleanField(default=False)),
                ('review', models.CharField(blank=True, default='Review', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
