# Generated by Django 4.2.6 on 2023-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_personalloan_loan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalloan',
            name='kyc_confirmed',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='kyc_submitted',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='review',
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='loan_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('in-active', 'In-active'), ('in-arrears', 'In-arrears'), ('paid-off', 'Paid-off'), ('written-off', 'Written-off')], default='In-active', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='loan_term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='Personal', max_length=20),
        ),
    ]
