# Generated by Django 4.2.6 on 2023-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_personalloan_kyc_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalloan',
            name='loan_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('In-active', 'In-active'), ('In-arrears', 'In-arrears'), ('Paid-off', 'Paid-off'), ('Written-off', 'Written-off')], default='In-active', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='loan_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], default='Personal', max_length=20),
        ),
    ]
